name: deploy

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
   rr_train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install requirements
        run: pip3 install -r requirements.txt
      
      - name: Fire SageMaker
        id: rr_train
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          AWS_DEFAULT_REGION: 'us-east-1'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tracking_server_arn: ${{ secrets.TRACKING_SERVER_ARN }}

        run: |
           python sagemaker_pipeline.py